extrn hBitmapHero: dword
extrn hBitmapTile: dword
extrn hIcon: dword
extrn hDCTile: HDC
extrn hDCFloor: HDC
extrn hDCWall: HDC
extrn hDCBraver: HDC
extrn hDCBackground: HDC
extrn hDCNumbers: ptr HDC
extrn hDCYellowDoor: HDC
extrn hDCBlueDoor: HDC
extrn hDCRedDoor: HDC
extrn hDCUpstair: HDC
extrn hDCDownstair: HDC

extrn hDCKeyYellow: HDC
extrn hDCKeyBlue: HDC
extrn hDCKeyRed: HDC

extrn hDCStoneRed: HDC
extrn hDCStoneBlue: HDC
extrn hDCBottleRed: HDC
extrn hDCBottleBlue: HDC

extrn hDCEnemy01: HDC
extrn hDCEnemy02: HDC
extrn hDCEnemy03: HDC
extrn hDCEnemy04: HDC
extrn hDCEnemy05: HDC
extrn hDCEnemy06: HDC
extrn hDCEnemy07: HDC
extrn hDCEnemy08: HDC
extrn hDCEnemy09: HDC

PreloadImages proto
PrepareDC proto hWnd: HWND